/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Wx100AudioProcessor.h"
#include "Wx100.h"

//==============================================================================
/**
*/
class Wx100AudioProcessorEditor  : public AudioProcessorEditor,
    private Slider::Listener, private ComboBox::Listener, public Timer
{
public:
    Wx100AudioProcessorEditor (Wx100AudioProcessor&);
    ~Wx100AudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider* slider) override;
    void comboBoxChanged (ComboBox* comboBox) override;
    void timerCallback();

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    Wx100AudioProcessor& processor;

    Slider amp[numOperators];
    Slider coarse[numOperators];
    Slider tuning[numOperators];
    Slider attack[numOperators];
    Slider decay[numOperators];
    Slider sustain[numOperators];
    Slider release[numOperators];
    Slider feedback;
    Slider lfoFrequency;
    ComboBox lfoShape;
    ComboBox algorithm;
    ComboBox scale;
    ComboBox scaleRoot;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Wx100AudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
